# Shared by the test files: the envelope fixtures the package ships, and the
# cases generated by the Python package with tools/generate-test-fixtures.py.

fixture <- function(name) {
  path <- system.file("schema", "fixtures", name, package = "dataexcept", mustWork = TRUE)
  paste(readLines(path, encoding = "UTF-8", warn = FALSE), collapse = "\n")
}

parity_cases <- function() {
  path <- testthat::test_path("fixtures", "observability-parity.json")
  jsonlite::read_json(path, simplifyVector = FALSE)
}

case_context <- function(case) {
  if (is.null(case$context)) {
    return(NULL)
  }
  do.call(operation_context, case$context)
}
