# Shared by the observability and OpenTelemetry tests: cases generated by the
# Python package with tools/generate-test-fixtures.py.

parity_cases <- function() {
  path <- testthat::test_path("fixtures", "observability-parity.json")
  jsonlite::read_json(path, simplifyVector = FALSE)
}

case_context <- function(case) {
  if (is.null(case$context)) {
    return(NULL)
  }
  do.call(operation_context, case$context)
}
