# Generate the documentation pages that come from the package itself.
#
#   Rscript tools/build-docs.R
#
# Reads man/*.Rd and writes docs/reference/<topic>.md plus an index page
# grouped by purpose, and writes docs/releases.md from NEWS.md. The Rd files are generated by roxygen from the R
# sources, so the site's reference cannot drift from the help pages as long as
# this script is run after roxygen (CI checks that the committed pages are
# current).

repo <- "https://github.com/DiogoRibeiro7/r-dataexcept"
man_dir <- "man"
out_dir <- file.path("docs", "reference")

# Topics in the order the reference index lists them.
groups <- list(
  "Classed errors" = c(
    "new_dataexcept_error", "validation_error", "data_frame_errors",
    "modelling_errors", "file_errors", "service_errors", "dataexcept_classes"
  ),
  "Failure metadata" = c("failure_metadata", "condition_failure"),
  "Envelopes" = c(
    "condition_to_envelope", "envelope_to_condition", "validate_envelope",
    "envelope_schema"
  ),
  "Observability" = c(
    "operation_context", "condition_to_event", "condition_to_otel_attributes",
    "record_otel_exception", "operation_context_from_otel"
  ),
  "Classed warnings" = "with_classed_warnings",
  "Redaction" = "redact_url",
  "Package" = "dataexcept-package"
)

tag <- function(x) {
  attr(x, "Rd_tag") %||% ""
}

`%||%` <- function(x, y) if (is.null(x)) y else x

# ---------------------------------------------------------------------------
# Links

rd_files <- sort(list.files(man_dir, pattern = "\\.Rd$", full.names = TRUE))
parsed <- lapply(rd_files, tools::parse_Rd)
topic_names <- vapply(parsed, function(rd) {
  paste(unlist(rd[vapply(rd, tag, "") == "\\name"][[1]]), collapse = "")
}, "")

local_aliases <- unlist(lapply(seq_along(parsed), function(i) {
  rd <- parsed[[i]]
  aliases <- vapply(rd[vapply(rd, tag, "") == "\\alias"], function(a) {
    paste(unlist(a), collapse = "")
  }, "")
  stats::setNames(rep(topic_names[[i]], length(aliases)), aliases)
}))

external_packages <- c("base", "stats", "utils", "methods", "jsonlite", "rlang")
base_r <- c("base", "stats", "utils", "methods")

external_alias_index <- local({
  index <- list()
  for (pkg in external_packages) {
    path <- tryCatch(find.package(pkg), error = function(e) NULL)
    if (is.null(path)) next
    aliases <- readRDS(file.path(path, "help", "aliases.rds"))
    for (alias in names(aliases)) {
      if (is.null(index[[alias]])) index[[alias]] <- c(pkg, aliases[[alias]])
    }
  }
  index
})

external_url <- function(pkg, file) {
  if (pkg %in% base_r) {
    sprintf("https://rdrr.io/r/%s/%s.html", pkg, file)
  } else {
    sprintf("https://rdrr.io/cran/%s/man/%s.html", pkg, file)
  }
}

resolve_link <- function(target, option) {
  if (!is.null(option) && startsWith(option, "=")) {
    target <- substring(option, 2L)
    option <- NULL
  }
  if (!is.null(option)) {
    pieces <- strsplit(option, ":", fixed = TRUE)[[1]]
    pkg <- pieces[1]
    file <- if (length(pieces) > 1) pieces[2] else target
    return(external_url(pkg, file))
  }
  if (!is.na(local_aliases[target])) {
    return(paste0(local_aliases[[target]], ".md"))
  }
  hit <- external_alias_index[[target]]
  if (!is.null(hit)) {
    return(external_url(hit[1], hit[2]))
  }
  NULL
}

# ---------------------------------------------------------------------------
# Rendering

escape_text <- function(x) {
  x <- gsub("\\", "\\\\", x, fixed = TRUE)
  x <- gsub("([*_`\\[\\]])", "\\\\\\1", x, perl = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  gsub(">", "&gt;", x, fixed = TRUE)
}

code_span <- function(text) {
  text <- gsub("\n", " ", text, fixed = TRUE)
  fence <- if (grepl("`", text, fixed = TRUE)) "``" else "`"
  pad <- if (startsWith(text, "`") || endsWith(text, "`")) " " else ""
  paste0(fence, pad, text, pad, fence)
}

raw_text <- function(x) {
  if (is.character(x)) {
    return(x)
  }
  t <- tag(x)
  if (t %in% c("\\dontshow", "\\testonly", "COMMENT")) {
    return("")
  }
  raw_children(x)
}

raw_children <- function(x) {
  paste(vapply(x, raw_text, ""), collapse = "")
}

render_children <- function(x) {
  paste(vapply(x, render, ""), collapse = "")
}

render_link <- function(x, as_code = FALSE) {
  label <- raw_children(x)
  target <- resolve_link(label, attr(x, "Rd_option"))
  text <- if (as_code) code_span(label) else escape_text(label)
  if (is.null(target)) text else sprintf("[%s](%s)", text, target)
}

render_code <- function(x) {
  # \code{\link{...}}, possibly followed by "()", renders as a linked code span.
  links <- Filter(function(k) tag(k) == "\\link", x)
  if (length(links) == 1L) {
    target <- resolve_link(raw_children(links[[1]]), attr(links[[1]], "Rd_option"))
    text <- code_span(trimws(raw_text(x)))
    return(if (is.null(target)) text else sprintf("[%s](%s)", text, target))
  }
  code_span(raw_text(x))
}

render_items <- function(x, numbered = FALSE) {
  items <- list()
  current <- NULL
  for (child in x) {
    if (tag(child) == "\\item") {
      if (!is.null(current)) items[[length(items) + 1L]] <- current
      current <- list()
    } else if (!is.null(current)) {
      current[[length(current) + 1L]] <- child
    }
  }
  if (!is.null(current)) items[[length(items) + 1L]] <- current
  lines <- vapply(seq_along(items), function(i) {
    body <- trimws(render(items[[i]]))
    body <- gsub("\n\\s*", " ", body)
    marker <- if (numbered) paste0(i, ".") else "-"
    paste(marker, body)
  }, "")
  paste0("\n\n", paste(lines, collapse = "\n"), "\n\n")
}

render_describe <- function(x) {
  entries <- Filter(function(k) tag(k) == "\\item", x)
  lines <- vapply(entries, function(item) {
    sprintf("%s\n:   %s", trimws(render(item[[1]])), trimws(gsub("\n\\s*", " ", render(item[[2]]))))
  }, "")
  paste0("\n\n", paste(lines, collapse = "\n\n"), "\n\n")
}

render <- function(x) {
  if (is.character(x)) {
    t <- tag(x)
    if (t == "TEXT") return(escape_text(x))
    if (t %in% c("RCODE", "VERB")) return(x)
    return("")
  }
  t <- tag(x)
  switch(t,
    "\\code" = render_code(x),
    "\\verb" = code_span(raw_text(x)),
    "\\samp" = code_span(raw_text(x)),
    "\\link" = render_link(x),
    "\\strong" = paste0("**", render_children(x), "**"),
    "\\bold" = paste0("**", render_children(x), "**"),
    "\\emph" = paste0("*", render_children(x), "*"),
    "\\dQuote" = paste0("“", render_children(x), "”"),
    "\\sQuote" = paste0("‘", render_children(x), "’"),
    "\\url" = sprintf("<%s>", raw_text(x)),
    "\\href" = sprintf("[%s](%s)", render(x[[2]]), raw_text(x[[1]])),
    "\\email" = sprintf("[%s](mailto:%s)", raw_text(x), raw_text(x)),
    "\\eqn" = code_span(raw_text(x[[1]])),
    "\\deqn" = paste0("\n\n", code_span(raw_text(x[[1]])), "\n\n"),
    "\\R" = "R",
    "\\dots" = "...",
    "\\ldots" = "...",
    "\\cr" = "  \n",
    "\\itemize" = render_items(x),
    "\\enumerate" = render_items(x, numbered = TRUE),
    "\\describe" = render_describe(x),
    "\\preformatted" = paste0("\n\n```r\n", sub("^\n", "", raw_text(x)), "\n```\n\n"),
    "\\if" = "",
    "\\ifelse" = render(x[[3]]),
    "\\out" = "",
    "\\special" = "",
    "\\subsection" = paste0(
      "\n\n### ", trimws(render(x[[1]])), "\n\n", render(x[[2]]), "\n\n"
    ),
    render_children(x)
  )
}

tidy <- function(text) {
  text <- gsub("[ \t]+\n", "\n", text)
  text <- gsub("\n{3,}", "\n\n", text)
  trimws(text)
}

section <- function(rd, name) {
  hits <- rd[vapply(rd, tag, "") == name]
  if (length(hits) == 0L) NULL else hits[[1]]
}

code_block <- function(x) {
  code <- trimws(raw_text(x), which = "right")
  code <- sub("^\n+", "", code)
  paste0("```r\n", code, "\n```")
}

render_arguments <- function(x) {
  items <- Filter(function(k) tag(k) == "\\item", x)
  entries <- vapply(items, function(item) {
    names <- trimws(strsplit(raw_text(item[[1]]), ",", fixed = TRUE)[[1]])
    term <- paste(vapply(names, code_span, ""), collapse = ", ")
    desc <- tidy(render(item[[2]]))
    desc <- gsub("\n", "\n    ", desc, fixed = TRUE)
    sprintf("%s\n:   %s", term, desc)
  }, "")
  paste(entries, collapse = "\n\n")
}

source_file <- function(path) {
  first <- readLines(path, n = 2L, warn = FALSE)
  hit <- regmatches(first, regexpr("R/[^ ]+\\.R", first))
  if (length(hit) == 0L) NULL else hit[[1]]
}

render_topic <- function(rd, path) {
  name <- topic_names[[match(path, rd_files)]]
  title <- tidy(render(section(rd, "\\title")))
  parts <- c(
    "<!-- Generated by tools/build-docs.R from the Rd files: do not edit by hand. -->",
    "",
    paste("#", title),
    ""
  )
  src <- source_file(path)
  if (!is.null(src)) {
    parts <- c(parts, sprintf(
      "<small>Source: [`%s`](%s/blob/main/%s) · Help: `?%s`</small>", src, repo, src, name
    ), "")
  }
  description <- section(rd, "\\description")
  if (!is.null(description)) parts <- c(parts, tidy(render(description)), "")

  usage <- section(rd, "\\usage")
  if (!is.null(usage) && nzchar(trimws(raw_text(usage)))) {
    parts <- c(parts, "## Usage", "", code_block(usage), "")
  }
  arguments <- section(rd, "\\arguments")
  if (!is.null(arguments)) {
    parts <- c(parts, "## Arguments", "", render_arguments(arguments), "")
  }
  value <- section(rd, "\\value")
  if (!is.null(value)) parts <- c(parts, "## Value", "", tidy(render(value)), "")
  details <- section(rd, "\\details")
  if (!is.null(details)) parts <- c(parts, "## Details", "", tidy(render(details)), "")
  for (extra in rd[vapply(rd, tag, "") == "\\section"]) {
    parts <- c(parts, paste("##", tidy(render(extra[[1]]))), "", tidy(render(extra[[2]])), "")
  }
  examples <- section(rd, "\\examples")
  if (!is.null(examples)) parts <- c(parts, "## Examples", "", code_block(examples), "")
  seealso <- section(rd, "\\seealso")
  if (!is.null(seealso)) parts <- c(parts, "## See also", "", tidy(render(seealso)), "")
  paste0(paste(parts, collapse = "\n"), "\n")
}

render_index <- function() {
  lines <- c(
    "<!-- Generated by tools/build-docs.R from the Rd files: do not edit by hand. -->",
    "",
    "# API reference",
    "",
    "Every exported function, generated from the package's help pages. In R, the",
    "same text is available with `?function_name`.",
    ""
  )
  listed <- unlist(groups)
  missing <- setdiff(topic_names, listed)
  if (length(missing) > 0L) {
    stop("Topics missing from the reference groups: ", paste(missing, collapse = ", "))
  }
  for (group in names(groups)) {
    lines <- c(lines, paste("##", group), "", "| Topic | Functions |", "| --- | --- |")
    for (topic in groups[[group]]) {
      rd <- parsed[[match(topic, topic_names)]]
      title <- tidy(render(section(rd, "\\title")))
      usage <- section(rd, "\\usage")
      fns <- if (is.null(usage)) character() else {
        calls <- regmatches(raw_text(usage), gregexpr("(?m)^[A-Za-z_.][A-Za-z0-9_.]*(?=\\()", raw_text(usage), perl = TRUE))[[1]]
        unique(calls)
      }
      fn_text <- if (length(fns)) paste(sprintf("`%s()`", fns), collapse = ", ") else ""
      lines <- c(lines, sprintf("| [%s](%s.md) | %s |", title, topic, fn_text))
    }
    lines <- c(lines, "")
  }
  paste0(paste(lines, collapse = "\n"), "\n")
}

dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
old <- list.files(out_dir, pattern = "\\.md$", full.names = TRUE)
unlink(old)
for (i in seq_along(parsed)) {
  writeLines(render_topic(parsed[[i]], rd_files[[i]]),
    file.path(out_dir, paste0(topic_names[[i]], ".md")),
    useBytes = TRUE
  )
}
writeLines(render_index(), file.path(out_dir, "index.md"), useBytes = TRUE)
cat(length(parsed), "reference pages written to", out_dir, "\n")

# Releases: NEWS.md with each heading moved down a level under a page title.
news <- readLines("NEWS.md", encoding = "UTF-8", warn = FALSE)
# The development heading is added straight after a release, before anything
# is under it; leave it off the page until it has entries.
dev <- which(news == "# dataexcept (development version)")
if (length(dev) == 1L) {
  following <- news[-seq_len(dev)]
  next_heading <- which(grepl("^# ", following))[1L]
  body <- if (is.na(next_heading)) following else following[seq_len(next_heading - 1L)]
  if (!any(nzchar(trimws(body)))) {
    news <- news[-seq(dev, dev + length(body))]
  }
}
in_code <- FALSE
for (i in seq_along(news)) {
  if (startsWith(news[[i]], "```")) in_code <- !in_code
  if (!in_code && grepl("^#{1,5} ", news[[i]])) news[[i]] <- paste0("#", news[[i]])
}
news <- sub("^## dataexcept \\(development version\\)", "## Development version", news)
news <- sub("^## dataexcept ", "## ", news)
writeLines(c(
  "<!-- Generated by tools/build-docs.R from NEWS.md: do not edit by hand. -->",
  "",
  "# Releases",
  "",
  "The changes in each version, from the package's `NEWS.md`.",
  "",
  news
), file.path("docs", "releases.md"), useBytes = TRUE)
cat("docs/releases.md written from NEWS.md\n")
